### ISSUE TITLE
Background of input elements in dark mode does not stand out

### ISSUE THREAD

**Issue by zachies** [AnnMarieW/dash-bootstrap-templates#15]
Thanks for making this library, it's incredibly helpful to have a consistent background when using Plotly figures! I'm currently noticing an issue where the background of input elements is the same as the container background when using dark backgrounds. If I remove the custom `dash-bootstrap-templates` CSS, the background of the input returns to white for contrast. In the image below, the input element is followed by a select element to show the difference.

<img width="184" alt="Screenshot 2023-09-15 at 9 54 15 AM" src="https://github.com/AnnMarieW/dash-bootstrap-templates/assets/13950829/cbe6f25a-711a-4b67-ac17-29a5687e8403">

```python
from dash import Dash
import dash_bootstrap_components as dbc

dbc_css = ("https://cdn.jsdelivr.net/gh/AnnMarieW/dash-bootstrap-templates@V1.0.8/dbc.min.css")
app = Dash(__name__, external_stylesheets=[dbc.themes.DARKLY, dbc_css])

app.layout = dbc.Container(
    [
        dbc.Input(placeholder="Test", class_name="mt-3"),
        dbc.Select(class_name="mt-3", options=[{
            "label": "Sample", "value": "sample"
        }]),
    ],
    fluid=True,
    class_name="dbc"
)

if __name__ == "__main__":
    app.run_server(debug=True)

```

It looks like line 64 of the stylesheet is causing this, is it intentional?
```css
/* Use this classname for dcc.Input */
.dbc input:not([type=radio]):not([type=checkbox]) {
  color: var(--bs-body-color) !important;
  background-color: var(--bs-body-bg) !important;
}
```
