### ISSUE TITLE
Issue: Compatibility with Python Versions Below 3.10

### ISSUE THREAD

**Issue by Anselmoo** [AnnMarieW/dash-bootstrap-templates#30]
#### Description

The `dash-bootstrap-templates` package currently uses the `|` operator for type unions, which is only supported in Python 3.10 and above. This makes the package incompatible with Python versions below 3.10. To ensure compatibility with Python 3.8 and 3.9, we should use the `Union` type from the `typing` module instead.

#### Proposed Solution

1. **Modify the code to use `Union` from the `typing` module:**

   Replace the `|` operator with `Union` in the `aio_theme_switch.py` file:

   **currently**:
     https://github.com/AnnMarieW/dash-bootstrap-templates/blob/eaab177b2d443e07f2143bca03264a04ced696d9/src/aio/aio_theme_switch.py#L35

    **suggestion**:

      ```python
       # aio_theme_switch.py

       from typing import Union

       def __init__(
            self,
            aio_id: str = str(uuid.uuid4()),
            themes: Union[tuple[str, str],list[str]] = (dbc.themes.CYBORG, dbc.themes.BOOTSTRAP),
            icons=None,
            switch_props: dict[str, any] = None,
            ):
            ...
      ```

2. **Update the `setup.cfg` file to specify the correct versions for different Python versions:**

   ```ini
   [options]
   python_requires = >=3.8

   install_requires =
       dash-bootstrap-templates<=1.1.2; python_version < '3.10'
       dash-bootstrap-templates>=1.2.0; python_version >= '3.10'
   ```
   https://github.com/AnnMarieW/dash-bootstrap-templates/blob/eaab177b2d443e07f2143bca03264a04ced696d9/setup.cfg#L11-L18

This might be an approach so that the 'dash-bootstrap-templates' package is compatible with Python 3.8 and 3.9, while still supporting the latest features in Python 3.10 and above.

---

####  Workaround

> [!NOTE]
> I currently have to split the dependency into two sections for Python versions below 3.10 and 3.10 and above. https://github.com/Anselmoo/spectrafit/pull/1432

   ```toml
   [tool.poetry.dependencies]
   python = ">=3.8"

   dash-bootstrap-templates = [
     { version = "<=1.1.2", markers = "python_version < '3.10'" },
     { version = "^1.2.0", markers = "python_version >= '3.10'" },
   ]
   ```
